---
title: "TP Spatial Econometrics"
format: html
editor: visual
---

# TP

#Importing data and packages

```{r}
# install les packages necessaires si ils ne sont pas deja installes
if (!require(sf))      install.packages("sf")
if (!require(mapview))      install.packages("mapview")

# charge les packages
library("sf")
library("mapview")



# chemin adaptatif vers les données 
path_data = paste(getwd(), "2025-07-metropolitan-outcomes.csv", sep = "/")

police = read.csv(path_data)

```

Counting number of NAs

```{r}
sum(is.na(police$Longitude))
sum(is.na(police$Latitude))
```

Filtering

```{r}
police_clean <- police[!is.na(police$Longitude) & !is.na(police$Latitude),]
rm(police, path_data)
gc()
```

Making it sf

```{r}
my_coords <- st_as_sf(police_clean, coords = c("Longitude", "Latitude"), crs = 4326)
```

Plot it

```{r}
mapview(my_coords)
```

# Data base presentation

# I/ Spatial Point Patterns Introduction

# II/ Complete Spatial Randomness

# III/ The k-function

# IV/ Intensity estimation

<<<<<<< HEAD


```{r}

my_coords2 <- st_as_sf(police_clean, coords = c("Longitude", "Latitude"), crs = 4326)


my_coords2 = st_transform(my_coords2, crs = 27700)
# Coordonnées
coords2 <- st_coordinates(my_coords2)



map <- ne_countries(type = "countries", country = "United Kingdom",
                    scale = "small", returnclass = "sf")


map <- st_transform(map, crs = "EPSG:27700")
win <- as.owin(map)


pp <- ppp(
  x = coords2[,1],
  y = coords2[,2],
  window = win
)




# Plot
plot(win, col = "lightgrey")
plot(pp, add = TRUE, pch = 20, col = "red",size = 0.8)




```


```{r}

lambdahat <- density(pp)
attr(lambdahat, "sigma")
```

```{r}
plot(lambdahat, main = "Default bandwidth")
plot(density(X, sigma = 1))
plot(density(X, sigma = 10))
plot(density(X, sigma = 100))
plot(density(X, sigma = 1000))
plot(density(X, sigma = 10000))
```




```{r}
table_var = list()
for (i in colnames(police_clean)) {
  table_var[[i]] = table(police_clean[i])
}
```

```{r}

table_var$Outcome.type

```





=======
>>>>>>> f753981706e8d2aacf63861165a47c2c2026d309
# Conclusion
